server:
  port: 7001

eureka:
  instance:
    hostname: localhost  # eureka 服务端的实例名称
  client:
    # false 表示自己是服务端注册中心，我们的职责就是维护服务实例并不需要去检索服务
    fetch-registry: false
    # false表示不向注册中心注册自己
    register-with-eureka: false
    service-url:
      # 设置与 eureka server 交互的地址查询服务和注册服务都需要依赖的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
